name: Packaging Pipeline
run-name: Packaging triggered by $ {{ github.actor }} ðŸ“¦
on:
  push:
    - v*

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: ${{ github.repository }}-backend # deo-webapp-ws25-backend
  # FRONTEND_IMAGE_NAME: ${{ github.repository }}-frontend # deo-webapp-ws25-frontend

jobs:
  build-and-push-backend-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5
      - name: Log in to container REGISTRY
        uses: docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        uses: docker/metadata-action
        with:
          images: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
      - name: Build and push images
        uses: docker/build-push-action
        with:
          context: ./Deo.Backend
          # file: ./Deo.Backend/Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
      - name: Attestation for backend image
        uses: actions/attest-build-provenance
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
